apiVersion: v1
kind: Service
metadata:
  name: {{ include "sre-hello-world.fullname" . }}-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sre-hello-world.labels" . | nindent 4 }}
    {{- include "sre-hello-world.frontend.selectorLabels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    {{- include "sre-hello-world.frontend.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
